
server:
  port: ${SEVER_PORT}

imp:
  imp_key: ${IMP_KEY}
  imp_secret: ${IMP_SECRET}


jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    expired-time-ms: ${JWT_EXPIRED_TIME}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
    producer:
      bootstrap-servers: ${KAFKA_SERVER}
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:${DB_TYPE}://${DB_ADDR}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: ${DB_DRIVER}

  jpa:
    database: ${DB_TYPE}
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false
