
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    config:
      name: ${APPLICATION_NAME}
      profile: ${APPLICATION_ENV}
  config:
    import: optional:configserver:${CONFIG_SERVER}
